version: '3'

services:
    misc-0:
        container_name: dns-check
        build: ./dns-check/
        image: registry.capture.tf:5000/wactf0x04/dns-check
        ports:
          - 80:8000
        deploy:
          resources:
            limits:
              cpus: '0.10'
              memory: 15M
            reservations:
              cpus: '0.05'
              memory: 10M
        cap_drop:
          - NET_RAW